apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-project-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      project: {{ .Values.project.slug }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              project: {{ .Values.project.slug }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-ingress-from-studio
  namespace: default
spec:
  podSelector:
    matchLabels:
      project: {{ .Values.project.slug }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: stackn-studio
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-egress-to-project
  namespace: default
spec:
  podSelector:
    matchLabels:
      project: {{ .Values.project.slug }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.project.slug }}