{{ if .Values.ingress.v1beta1 }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-mlflow-ingress
  namespace: {{ .Values.namespace }}
  labels:
    io.kompose.service: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
    nginx.ingress.kubernetes.io/auth-url: "{{ .Values.global.protocol }}://{{ .Values.global.auth_domain }}:8080/auth/?release={{ .Values.release }}"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.global.domain }}/accounts/login/?next=$scheme%3A%2F%2F$host"
    #nginx.ingress.kubernetes.io/auth-response-headers: X-Forwarded-Host
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Values.service.name }}-{{ .Values.app_name }} 
            servicePort: 80
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Release.Name }}.{{ .Values.global.domain }}

{{ else }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-server
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
    nginx.ingress.kubernetes.io/auth-url: "{{ .Values.global.protocol }}://{{ .Values.global.auth_domain }}:8080/auth/?release={{ .Values.release }}"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.global.domain }}/accounts/login/?next=$scheme%3A%2F%2F$host"
    #nginx.ingress.kubernetes.io/auth-response-headers: X-Forwarded-Host
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ .Values.service.name }}
              port:
                number: 5000
          pathType: ImplementationSpecific
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Release.Name }}.{{ .Values.global.domain }}
apiVersion: networking.k8s.io/v1

{{- end }}