
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-gatekeeper
  namespace: {{ .Values.namespace }}
data:
  # Configuration values can be set as key-value properties
  gatekeeper.yaml: |-
    enable-default-deny: false
    {{ if .Values.permissions.private }}
    resources:
    - uri: /registry/*
      roles:
      - {{ .Values.gatekeeper.client_id }}:owner
    {{ else if .Values.permissions.project }}
    resources:
    - uri: /registry/*
      roles:
      - {{ .Values.project.slug }}:admin
      - {{ .Values.project.slug }}:member
      - {{ .Values.project.slug }}:guest
      require-any-role: true
    {{ else if .Values.permissions.public }}
    enable-default-deny: false
    {{ else }}
    enable-default-deny: true
    {{ end }}
    discovery-url: {{ .Values.gatekeeper.auth_endpoint }}/{{ .Values.gatekeeper.realm }}
    {{ if .Values.permissions.project }}
    client-id: {{ .Values.project.client_id }}
    client-secret: {{ .Values.project.client_secret }}
    {{ else }}
    client-id: {{ .Values.gatekeeper.client_id }}
    client-secret: {{ .Values.gatekeeper.client_secret }}
    {{ end }}
    listen: 0.0.0.0:{{ .Values.gatekeeper.port }}
    enable-session-cookies: true
    enable-logging: true
    enable-json-logging: true
    upstream-url: http://127.0.0.1:1234
    enable-authorization-header: true
    add-claims:
      - email
    {{ if .Values.gatekeeper.skip_tls }}
    skip-openid-provider-tls-verify: true
    {{ end }}