apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: pacman
      project: {{ .Values.project.slug }}
      type: app
      pod: pacman
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: pacman
        project: {{ .Values.project.slug }}
        type: app
        pod: pacman
    spec:
      containers:
      - name: gatekeeper
        image: scaleoutsystems/gatekeeper:latest
        imagePullPolicy: Always
        args:
          - --config=/etc/secrets/gatekeeper.yaml
        ports:
          - containerPort: 9090
        volumeMounts:
        - name: gatekeeper-config
          mountPath: /etc/secrets/

      - name: pacman
        image: scaleoutsystems/pacman:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      volumes:
      - name: gatekeeper-config
        configMap:
          name: {{ .Release.Name }}-gatekeeper-config
