replicas: 1
appname: app-name
namespace: default
visibility: private

resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 700m
    memory: 2Gi

global:
  domain: global.domain

registry:
  secure: False
  host: stack-docker-registry:5000

imagePullSecret: regcred

project:
  slug: project-slug

deployment:
  image: scaleoutsystems/default-python:latest
  version: version
  name: deployment-name
  endpoint: deployment-endpoint
  path: deployment-path
  port: 8501

context:
  image: context-image

model:
  name: name
  version: version
  release_type: release_type
  description: short-description
  url: url
  access_key: key
  secret_key: secret
  bucket: bucket
  obj: obj

model_card:
  enabled: false
  path: model-card

gatekeeper:
  image: scaleoutsystems/gatekeeper:latest
  client_secret: 75ffdab1-605a-49a9-9544-4807072d0908
  client_id: wetty-test
  auth_endpoint: https://keycloak.local.stackn.dev/auth/realms
  skip_tls: 0
  port: 9090


# extraEnv: |
#   - name: LICENSE_FILE
#     value: SOMESTRING
