apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.release }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: pebble
      project: {{ .Values.project.slug }}
      type: app
      pod: pebble
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8501"
      labels:
        release: {{ .Release.Name }}
        app: pebble
        project: {{ .Values.project.slug }}
        type: app
        pod: pebble
    spec:
      volumes:
      - name: minio-config
        configMap:
          name: {{ .Values.release }}-minio
      - name: config
        configMap:
          name: {{ .Values.release }}-config
      containers:
      - name: iotex-hmq
        image: scaleoutsystems/iotex-hmq:latest
        imagePullPolicy: Always
        command: ['/hmq', '-c', '/config/config.json']
        volumeMounts:
        - name: minio-config
          mountPath: /plugins/minio/minio.json
          subPath: minio.json
        - name: config
          mountPath: /config/config.json
          subPath: config.json
      - name: api-server
        image: scaleoutsystems/iotex-blockchain-data:latest
        imagePullPolicy: Always
        env:
        - name: IO_ENDPOINT
          value: ""
        - name: CONTRACT_ADDRESS
          value: ""
        - name: VAULT_ADDRESS
          value: ""
        - name: GAS_PRICE
          value: "1000000000000"
        - name: GAS_LIMIT
          value: "5000000"
        - name: SLEEP_INTERVAL
          value: "10"