apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak-proxy-svc
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Release.Name }}-keycloak-proxy-svc
spec:
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    release: {{ .Release.Name }}
    pod: studio