apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - {{ .Values.accessModes }}
  {{ if .Values.volume.storageClass }}
  storageClassName: {{ .Values.volume.storageClass }}
  {{ else }}
  storageClassName: {{ .Values.storageClass | default "default" }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
status: {}
