namespace: default
appname: standardapp
project:
  name: project
  slug: project-slug

app:
  resources:
    requests:
      memory: 1024Mi
      cpu: 1.0
    limits:
      memory: 1024Mi
      cpu: 1.0

  gpu:
    enabled: false

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: acceleration
            operator: In
            values:
            - gpu

imagePullSecrets:
  - name: regcred

ingress:
  v1beta1: false
  secretName: prod-ingress

s3sync:
  image: scaleoutsystems/s3-sync:latest

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
