apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: mongodb
      project: {{ .Values.project.slug }}
      type: app
      pod: mongodb
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: mongodb
        project: {{ .Values.project.slug }}
        type: app
        pod: mongodb
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - image: mongo:3-xenial
        imagePullPolicy: IfNotPresent
        name: {{ .Release.Name }}
        args:
          {{- range $key, $value := .Values.apps.volumeK8s }}
          - --dbpath=/home/stackn/{{ $key }}
          {{- end }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.credentials.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.credentials.password }}
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        {{- range $key, $value := .Values.apps.volumeK8s }}
        - name: {{ $key }}
          mountPath: /home/stackn/{{ $key }}
        {{- end }}
        # {{- with .Values.extraVolumeMounts }}
        # {{- tpl . $ | nindent 8 }}
        # {{- end }}
      hostname: {{ .Release.Name }}
      restartPolicy: Always
      volumes:
      {{- range $key, $value := .Values.apps.volumeK8s }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
      # {{- with .Values.extraVolumes }}
      # {{- tpl . $ | nindent 6 }}
      # {{- end }}
status: {}