apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.release }}
spec:
  ports:
  - name: 
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    release: {{ .Values.release }}