namespace: default
appname: ubuntu-wetty
project:
  name: project
  slug: project-slug

app:
  resources:
    requests:
      memory: 1024Mi
      cpu: 1.0
    limits:
      memory: 1024Mi
      cpu: 1.0

  gpu:
    enabled: false

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: acceleration
            operator: In
            values:
            - gpu

imagePullSecrets:
  - name: regcred

minio:
  access_key: minio
  secret_key: minio123
  bucket: dataset

ingress:
  v1beta1: false
  secretName: prod-ingress

s3sync:
  image: scaleoutsystems/s3-sync:latest