kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-rp-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |-
    pid /tmp/nginx.pid;
    worker_processes 1;
    events { worker_connections 1024; }
    http {
        server {
            listen 1234;

            client_max_body_size 500M;
            large_client_header_buffers 4 128k;

            location / {
                proxy_pass http://127.0.0.1:{{ .Values.default_values.port }};
            }
            {{ if .Values.model_card.enabled }}
            location ~ ^/model-card(/?)(.*) {
              proxy_pass http://127.0.0.1:80/$2;
            }
            {{ end }}
        }
    }