apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ $.Release.Name }}
      app: rstudio
      project: {{ $.Values.project.slug }}
      type: app
      pod: rstudio
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        # prometheus.io/port: "8501"
      labels:
        release: {{ $.Release.Name }}
        app: rstudio
        project: {{ $.Values.project.slug }}
        type: app
        pod: rstudio
    spec:
    {{ if .Values.labs.gpu.enabled }}
      affinity:
        {{ .Values.labs.affinity | toYaml | nindent 8 | trim }}
    {{ end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      #securityContext:
      #  runAsUser: 65533  # to allow read of ssh key
      containers:
      - name: reverse-proxy
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: rp-conf
          mountPath: /etc/nginx
      - name: rstudio
        image: {{ .Values.environment.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8787
        env:
        - name: DISABLE_AUTH
          value: "true"
        resources:
          requests:
            memory: {{ .Values.flavor.requests.memory | default "256Mi" }}
            cpu: {{ .Values.flavor.requests.cpu | default "200m" }}
            {{if .Values.flavor.gpu.enabled }}
            nvidia.com/gpu: "1"
            {{ end }}
          limits:
            memory: {{ .Values.flavor.limits.memory | default "256Mi" }}
            cpu: {{ .Values.flavor.limits.cpu | default "200m" }}
            {{ if .Values.flavor.gpu.enabled }}
            nvidia.com/gpu: "1"
            {{ end }}
        workingDir: /home/rstudio
        volumeMounts:
        # - name: stacknconfig
        #   mountPath: /home/jovyan/.scaleout/
        # - name: projectconfig
        #   mountPath: /home/jovyan/.scaleout/stackn/projects/
        # - name: userconfig
        #   mountPath: /home/jovyan/.scaleout/stackn/
        #   readOnly: true
        # - name: cli-working-dir
        #   mountPath: /home/.scaleout/
        {{- range $key, $value := .Values.apps.volume }}
        - name: {{ $key }}
          mountPath: /home/rstudio/{{ $key }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
      # - name: stacknconfig
      #   configMap:
      #     name: {{ .Values.project.name }}-project-settings-configmap
      # - name: projectconfig
      #   configMap:
      #     name: {{ .Release.Name }}-project-labs-stackn-settings
      # - name: userconfig
      #   secret:
      #     secretName: {{ .Release.Name }}-project-labs-user-settings
      # - name: cli-working-dir
      #   emptyDir: {}
      - name: rp-conf
        configMap:
          name: {{ .Release.Name }}-rp-config
      {{- range $key, $value := .Values.apps.volume }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
