kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cli-config
  namespace: {{ .Values.namespace }}
data:
  # Configuration values can be set as key-value properties
  stackn.json: |-
    {
        "{{ .Values.cli_setup.url }}": {
            "STACKN_URL": "{{ .Values.cli_setup.url }}",
            "STACKN_PROJECT": "{{ .Values.cli_setup.project }}",
            "STACKN_ACCESS_TOKEN": "{{ .Values.cli_setup.token }}",
            "STACKN_REFRESH_TOKEN": "{{ .Values.cli_setup.refresh_token }}",
            "STACKN_USER": "{{ .Values.cli_setup.user }}"
        },
        "current": {
            "STACKN_URL": "{{ .Values.cli_setup.url }}",
            "STACKN_PROJECT": "{{ .Values.cli_setup.project }}",
            "STACKN_SECURE": "{{ .Values.cli_setup.secure }}"
        }
    }