{{ if .Values.ingress.v1beta1 }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    io.kompose.service: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
    nginx.ingress.kubernetes.io/auth-url: "http://studio.{{ .Values.global.domain }}:8080/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://studio.{{ .Values.global.domain }}:8080/auth/start?rd=$escaped_request_uri"
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-lab
            servicePort: 80
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Release.Name }}.{{ .Values.global.domain }}

{{ else }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.global.domain }}:8080/auth/"
    nginx.ingress.kubernetes.io/auth-signin: "http://{{ .Values.global.domain }}:8080/accounts/login/?next=$scheme%3A%2F%2F$host"
    #nginx.ingress.kubernetes.io/auth-response-headers: X-Forwarded-Host
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ .Release.Name }}-lab
              port:
                number: 80
          pathType: ImplementationSpecific
  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Release.Name }}.{{ .Values.global.domain }}

{{- end }}