apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-tf-svc
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.appname }}
    app: tensorflow-serve
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  selector:
    release: {{ $.Release.Name }}