apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: mongodb
      project: {{ .Values.project.slug }}
      type: app
      pod: mongodb
  template:
      labels:
        release: {{ .Release.Name }}
        app: mongodb
        project: {{ .Values.project.slug }}
        type: app
        pod: mongodb
    spec:
      containers:
      - image: mongo:3-xenial
        name: {{ .Release.Name }}
        args:
          {{- range $key, $value := .Values.apps.volume }}
          - --dbpath=/home/stackn/{{ $key }}
          {{- end }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.credentials.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.credentials.password }}
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        {{- range $key, $value := .Values.apps.volume }}
        - name: {{ $key }}
          mountPath: /home/stackn/{{ $key }}
        {{- end }}
        # {{- with .Values.extraVolumeMounts }}
        # {{- tpl . $ | nindent 8 }}
        # {{- end }}
      hostname: {{ .Release.Name }}
      restartPolicy: Always
      volumes:
      {{- range $key, $value := .Values.apps.volume }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
      # {{- with .Values.extraVolumes }}
      # {{- tpl . $ | nindent 6 }}
      # {{- end }}
status: {}
