apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Release.Name }}
    app: minio
    project: {{ .Values.project.slug }}
    type: secret
type: Opaque
data:
  accesskey: {{ if .Values.credentials.access_key }}{{ .Values.credentials.access_key | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  secretkey: {{ if .Values.credentials.secret_key }}{{ .Values.credentials.secret_key | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}