apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Values.namespace }}
data:
  config.json: |-
    {
      "auths": {
        {{- range $key, $value := .Values.apps.docker_registry }}
        {{- $_ := set $ "key" $key }}
        {{- $_ := set $ "value" $value }}
        "{{ $value.release }}.{{ $.Values.global.domain }}": {
          "auth": "{{ tpl ("{{ .value.credentials.username }}:{{ .value.credentials.password }}") $ | b64enc }}"
        }
        {{- end }}
      }
    }