apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: lab
      project: {{ .Values.project.slug }}
      type: app
      pod: lab
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        # prometheus.io/port: "8501"
      labels:
        release: {{ .Release.Name }}
        app: lab
        project: {{ .Values.project.slug }}
        type: app
        pod: lab
    spec:
    {{ if .Values.labs.gpu.enabled }}
      affinity:
        {{ .Values.labs.affinity | toYaml | nindent 8 | trim }}
    {{ end }}
    {{ if .Values.environment.registry }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-pull-secret
    {{ end }}
      containers:
      - name: gatekeeper
        image: scaleoutsystems/gatekeeper:latest
        imagePullPolicy: Always
        args:
          - --config=/etc/secrets/gatekeeper.yaml
        ports:
          - containerPort: 9090
        volumeMounts:
        - name: gatekeeper-config
          mountPath: /etc/secrets/
      - name: labs
        image: {{ .Values.environment.repository }}/{{ .Values.environment.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: NOTEBOOK_PASSWD_SHA1
          value: ""
        - name: NOTEBOOK_TOKEN
          value: ""
        - name: MLFLOW_TRACKING_URI
          value: {{ .Values.mlflow.url }}
        - name: MLFLOW_TRACKING_USERNAME
          value: {{ .Values.mlflow.username }}
        - name: MLFLOW_TRACKING_PASSWORD
          value: {{ .Values.mlflow.password }}
        - name: MLFLOW_S3_ENDPOINT_URL
          value: {{ .Values.mlflow.s3url }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.mlflow.access_key }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.mlflow.secret_key }}
        resources:
          requests:
            memory: {{ .Values.flavor.requests.memory | default "256Mi" }}
            cpu: {{ .Values.flavor.requests.cpu | default "200m" }}
            {{if .Values.flavor.gpu.enabled }}
            nvidia.com/gpu: "1"
            {{ end }}
          limits:
            memory: {{ .Values.flavor.limits.memory | default "256Mi" }}
            cpu: {{ .Values.flavor.limits.cpu | default "200m" }}
            {{if .Values.flavor.gpu.enabled }}
            nvidia.com/gpu: "1"
            {{ end }}
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - -c
                - mkdir -p /home/jovyan/.scaleout && cp -n /stackn.json /home/jovyan/.scaleout/stackn.json
        workingDir: /home/jovyan/work
        volumeMounts:
        - name: cli-config-vol
          mountPath: /home/jovyan/.scaleout
        - name: cli-config
          mountPath: /stackn.json
          subPath: stackn.json
        - name: jupyterconf
          mountPath: /etc/jupyter/jupyter_notebook_config.py
          subPath: jupyter_notebook_config.py

        {{- range $key, $value := .Values.apps.volume }}
        - name: {{ $key }}
          mountPath: /home/jovyan/work/{{ $key }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
      - name: cli-config-vol
        emptyDir: {}
      - name: cli-config
        configMap:
          name: {{ .Release.Name }}-cli-config
      - name: gatekeeper-config
        configMap:
          name: {{ .Release.Name }}-gatekeeper-config
      - name: jupyterconf
        configMap:
          name: {{ .Release.Name }}-jupyter-configmap
      {{- range $key, $value := .Values.apps.volume }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
